version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=support
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "54321:5432"
